color0 #232627
color1 #ed1515
color2 #11d116
color3 #f67400
color4 #1d99f3
color5 #9b59b6
color6 #1abc9c
color7 #fcfcfc
color8 #7f8c8d
color9 #c0392b
color10 #1cdc9a
color11 #fdbc4b
color12 #3daee9
color13 #8e44ad
color14 #16a085
color15 #ffffff
background #232627
selection_foreground #ffffff
cursor #3daee9
cursor_text_color #232627
foreground #fcfcfc
selection_background #3daee9
active_border_color #3daee9
inactive_border_color #1d99f3

active_tab_foreground   #141618
active_tab_background   #3daee9
inactive_tab_foreground #a1a9b1
inactive_tab_background #292d32
cursor_trail_color      #a1a9b1
