color0 #120f18
color1 #d94a59
color2 #3dcc61
color3 #ffd400
color4 #4ea8de
color5 #5a189a
color6 #04a6c2
color7 #e1e2d5
color8 #262427
color9 #ff707f
color10 #61f285
color11 #f2e661
color12 #48bfe3
color13 #7b2cbf
color14 #00b2ca
color15 #f1faee
background #1d1b1d
selection_foreground #1d1b1d
cursor #e1e2d5
cursor_text_color #1d1b1d
foreground #e1e2d5
selection_background #e1e2d5
active_border_color #e1e2d5
inactive_border_color #2d2a2e

active_tab_foreground   #1d1b1d
active_tab_background   #e1e2d5
inactive_tab_foreground #e1e2d5
inactive_tab_background #262427
cursor_trail_color      #e1e2d5
